/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_netease_soundtouch_SoundTouch */

#ifndef _Included_com_netease_soundtouch_SoundTouch
#define _Included_com_netease_soundtouch_SoundTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netease_soundtouch_SoundTouch
 * Method:    setTempo
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_netease_soundtouch_SoundTouch_setTempo
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_netease_soundtouch_SoundTouch
 * Method:    setPitchSemiTones
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_netease_soundtouch_SoundTouch_setPitchSemiTones
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_netease_soundtouch_SoundTouch
 * Method:    putBytes
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_netease_soundtouch_SoundTouch_putBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_netease_soundtouch_SoundTouch
 * Method:    getBytes
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_netease_soundtouch_SoundTouch_getBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_netease_soundtouch_SoundTouch
 * Method:    newInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_netease_soundtouch_SoundTouch_newInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_netease_soundtouch_SoundTouch
 * Method:    deleteInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_netease_soundtouch_SoundTouch_deleteInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_netease_soundtouch_SoundTouch
 * Method:    flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_netease_soundtouch_SoundTouch_flush
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
